language: node_js
node_js:
  - node
  - '8.11.3'
os:
  - osx
  - linux
env:
  - TARGET_ARCH=x64
before_install:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
install:
  - npm install
script:
  - npm run test
notifications:
email: false